version: 0.0.{build}
branches:
  only:
  - test-bindgen-fix
image: Visual Studio 2017
environment:
  VCPKGRS_DYNAMIC: 1
  RUST_VERSION: stable
  matrix:
  - TARGET: i686-pc-windows-msvc
    VCPKG_TARGET: x86-windows
  - TARGET: i686-pc-windows-msvc
    VCPKG_TARGET: x86-windows
    RUST_VERSION: beta
  - TARGET: i686-pc-windows-msvc
    VCPKG_TARGET: x86-windows
    RUST_VERSION: nightly
install:
- cmd: >-
    curl -sSf -o rustup-init.exe https://win.rustup.rs/

    rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%

    set PATH=%PATH%;%USERPROFILE%\.cargo\bin

    rustc -Vv

    cargo -V

    vcpkg install libsodium:%VCPKG_TARGET%
cache:
- C:\Users\appveyor\.cargo\registry
- target
build_script:
- cmd: >-
    cargo build --target %TARGET%

    cargo build --target %TARGET% --release
test_script:
- cmd: >-
    cargo test --target %TARGET%

    cargo test --target %TARGET% --release